# Include service and deployment in one file because they are tied together
apiVersion: v1
kind: Service
metadata:
  name: flasknginx-service
spec:
  type: NodePort #Making accessible from the browser external service
  selector:  #Connecting service to pods
    app: flaskgun
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  #container port of deployment
      nodePort: 30001  #Exposes the service on each NodeIp as static IP
---
apiVersion: apps/v1
kind: Deployment  #Blueprint for the pod
metadata:
  name: flasknginx-deployment
  labels:
    app: flaskgun
spec:
  replicas: 2
  selector:
    matchLabels: #Which pods belongs to which deployment
      app: flaskgun
  template: #configuracion of the pod
    metadata:
      labels:  #required field for pods
        app: flaskgun
    spec:
      containers:  #which image, which port for the container
      - name: flasknginx
        image: "zelfick/flasknginx"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: flaskgun
        image: "zelfick/flaskgun"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
